name: Notify Parent Repository on Publish

on:
  release:
    types: [published]
  workflow_run:
    workflows: ["Publish Package"]
    types: [completed]

jobs:
  notify-parent:
    if: ${{ github.event_name == 'release' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Get package info
        id: package
        run: |
          echo "name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "version=latest" >> $GITHUB_OUTPUT
          fi
          
      - name: Notify h1b-visa-analysis
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ChaseNoCap/h1b-visa-analysis
          event-type: package-published
          client-payload: |
            {
              "package": "${{ steps.package.outputs.name }}",
              "version": "${{ steps.package.outputs.version }}",
              "repository": "${{ github.repository }}"
            }