#!/bin/bash

echo "🔍 Testing Renovate Configuration"
echo "================================="
echo ""

# Check if Renovate has created any branches
echo "1️⃣ Checking for Renovate branches..."
git ls-remote --heads origin | grep renovate || echo "No Renovate branches found yet"

echo ""
echo "2️⃣ Checking for Renovate PRs..."
gh pr list --search "author:app/renovate" --state all || echo "No Renovate PRs found"

echo ""
echo "3️⃣ Checking for Dependency Dashboard..."
gh issue list --search "author:app/renovate" || echo "No Renovate dashboard found"

echo ""
echo "📋 Manual Renovate Trigger Options:"
echo ""
echo "Option 1: Force Renovate to run (if you have access):"
echo "  - Go to: https://app.renovatebot.com/dashboard"
echo "  - Find 'ChaseNoCap/h1b-visa-analysis'"
echo "  - Click 'Run Now' or similar option"
echo ""
echo "Option 2: Trigger via empty commit:"
echo "  git commit --allow-empty -m 'chore: trigger renovate'"
echo "  git push"
echo ""
echo "Option 3: Check Renovate logs:"
echo "  - Visit: https://app.renovatebot.com/dashboard#github/ChaseNoCap/h1b-visa-analysis"
echo "  - Look for recent job runs"
echo "  - Check for authentication errors"
echo ""
echo "🔐 If Authentication Fails, Add Secret in Mend Portal:"
echo "=================================================="
echo "1. Go to: https://developer.mend.io/"
echo "2. Sign in with GitHub"
echo "3. Navigate to your organization settings"
echo "4. Find 'Secrets' or 'Repository Secrets'"
echo "5. Add new secret:"
echo "   - Name: GITHUB_COM_TOKEN"
echo "   - Value: Your PAT token (ghp_...)"
echo "   - Scope: h1b-visa-analysis repository"
echo ""
echo "The secret name MUST be exactly: GITHUB_COM_TOKEN"
echo "(This matches the {{ secrets.GITHUB_COM_TOKEN }} in renovate.json)"