import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function generateReport() {
  try {
    // Create dist directory if it doesn't exist
    const distDir = path.join(__dirname, '..', 'dist');
    if (!fs.existsSync(distDir)) {
      fs.mkdirSync(distDir, { recursive: true });
    }

    // Generate basic hello world report
    const reportContent = `# H1B Visa Analysis Report

## Hello World

This is a placeholder report generated by the H1B Report Generator.

Generated on: ${new Date().toISOString()}

### Coming Soon
- Integration with prompts-shared
- Integration with markdown-compiler  
- Integration with report-components
`;

    // Write report to dist directory
    const outputPath = path.join(distDir, 'report.md');
    fs.writeFileSync(outputPath, reportContent);

    console.log(`✅ Report generated successfully at: ${outputPath}`);
  } catch (error) {
    console.error('❌ Error generating report:', error);
    process.exit(1);
  }
}

// Run the generator
generateReport();