name: Publish All Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version bump type for all packages'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - di-framework
          - test-mocks
          - test-helpers
          - file-system
          - cache
          - report-templates
          - event-system
          - prompts
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build all packages
        run: npm run build:all
        
      - name: Version and Publish ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          npm publish
          
      - name: Commit version changes
        run: |
          git add packages/*/package.json
          git commit -m "chore: bump versions for release"
          git push